spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        test-data-output:
          destination: test_data_channel
          contentType: application/json

  #mysql
  datasource:
    url: jdbc:mysql://localhost:3306/uniapi
    username: root
    password: monaco1@Bbet
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

#  datasource:
#    url: jdbc:mysql://192.168.10.145:3307/uniapi
#    username: dev
#    password: dev123
#    hikari:
#      connection-timeout: 30000
#      idle-timeout: 600000
#      max-lifetime: 1800000

  #mongo db
  data:
    mongodb:
      database: testDB
      port: 27017

server:
  port: 9090


  # spring.cloud.stream.bindings.<channelName>.
  # destination --> The target destination of a channel on the bound middleware (e.g., the RabbitMQ exchange or Kafka topic).
  # Just Update the username and password